// Code generated by "stringer -type OrderSide"; DO NOT EDIT.

package robinhood

import "strconv"

const _OrderSide_name = "SellBuy"

var _OrderSide_index = [...]uint8{0, 4, 7}

func (o OrderSide) String() string {
	o -= 1
	if o < 0 || o >= OrderSide(len(_OrderSide_index)-1) {
		return "OrderSide(" + strconv.FormatInt(int64(o+1), 10) + ")"
	}
	return _OrderSide_name[_OrderSide_index[o]:_OrderSide_index[o+1]]
}
